name: 3wrobot_ni
observation_target: = []
sampling_time: 0.01
time_final: 5
safe_decay_param_ex_post: 1.0E-3
safe_decay_param_predictive: 1.0E-3
critic_penalty_param: 0
critic_regularization_param: 0
is_dynamic_decay_rate: True
lb_parameter: 1.0E-6
ub_parameter: 1.0E+3
is_use_derivative: True

data_buffer_size: 400

grid_dim%%: 4
v_min%%: -25.
v_max%%: 25.
omega_min%%: -5.
omega_max%%: 5.

actions_grid: = numpy.vstack(map(numpy.ravel, numpy.meshgrid(numpy.linspace(${.v_min%%}, ${.v_max%%}, ${.grid_dim%%}), numpy.linspace(${.omega_min%%}, ${.omega_max%%}, ${.grid_dim%%}))))
diag_scale_coef: 5.

calf_data_buffer_size: 8
single_weight_min: 1.0E-6
single_weight_max: 1.0E+2

fps: 25
mpc_prediction_horizon: 5

system_visualization_dashboard:
  _target_: rcognita.visualization.dashboards.RobotTrackingDasboard
  time_start: $ simulator.time_start
  x_max: 10
  x_min: -10
  y_max: 10
  y_min: -10
  scenario: ~ scenario